services:
  web-consumer:
    build: ./WebConsumer
    env_file: ./WebConsumer/.env
    ports:
      - "8082:8082"
  
  live-data:
    build: ./LiveData
    env_file: ./LiveData/.env
    ports:
      - "8080:8080"

  past-data-service:
    build: ./PastDataService
    env_file: ./PastDataService/.env
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
  prometheus:
    image: prom/prometheus
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
